name: milwaukeetool Auto Sign

on:
  schedule:
    - cron: '30 22,4,10 * * *'  # 对应北京时间 06:30 12:30 18:30
  workflow_dispatch:

jobs:
  sign:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai  # 系统时区统一东八区

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run Sign Script
      env:
        SEND_KEY_LIST: ${{ secrets.SEND_KEY_LIST }}
        SERVERCHAN_SENDKEY: ${{ secrets.SERVERCHAN_SENDKEY }}
        MILWAUKEEtool_CLIENT_ID: ${{ secrets.MILWAUKEEtool_CLIENT_ID }}  # 修正：MILWAUKEE（2个E+1个K）
        MILWAUKEEtool_TOKEN_LIST: ${{ secrets.MILWAUKEEtool_TOKEN_LIST }} # 修正：MILWAUKEE（2个E+1个K）
        WECHAT_WEBHOOK_URL: ${{ secrets.WECHAT_WEBHOOK_URL }}
        DINGTALK_WEBHOOK_URL: ${{ secrets.DINGTALK_WEBHOOK_URL }}
      run: |
        python milwaukeetool-sign.py
